package de.rocovomo.jnect.kinect.api;

public enum KinectStatus {
	SPEECH_RECOGNITION_STARTED, SPEECH_RECOGNITION_STOPPED, GESTURE_RECOGNITION_STARTED, GESTURE_RECOGNITION_STOPPED, KINECT_STARTED, KINECT_STOPPED
}
