set DOCUMENT_NAME=document
del *.aux
rmdir \tmp /S /Q
rmdir tmp
del %DOCUMENT_NAME%.acn 
del %DOCUMENT_NAME%.glo 
del %DOCUMENT_NAME%.ist 
del %DOCUMENT_NAME%.lof 
del %DOCUMENT_NAME%.log 
del %DOCUMENT_NAME%.lot 
del %DOCUMENT_NAME%.lol 
del %DOCUMENT_NAME%.out 
del %DOCUMENT_NAME%.toc 
del %DOCUMENT_NAME%.alg 
del %DOCUMENT_NAME%.glg 
del %DOCUMENT_NAME%.gls 
del %DOCUMENT_NAME%.acr 
:del %DOCUMENT_NAME%.pdf 
del %DOCUMENT_NAME%.bbl 
del %DOCUMENT_NAME%.blg 
del %DOCUMENT_NAME%.dvi
del %DOCUMENT_NAME%.idx
del %DOCUMENT_NAME%.ilg
del %DOCUMENT_NAME%.ind
del %DOCUMENT_NAME%.synctex.gz
del %DOCUMENT_NAME%.xdy