This is makeindex, version 2.15 [TeX Live 2010] (kpathsea + Thai support).
Scanning style file ./document.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file document.acn....done (43 entries accepted, 0 rejected).
Sorting entries....done (265 comparisons).
Generating output file document.acr....done (32 lines written, 0 warnings).
Output written in document.acr.
Transcript written in document.alg.
